---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: argo-child
  namespace: argocd
  labels:
    {{- include "argo-parent.labels" . | nindent 4 }}
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: child
  project: default
  sources:
    - path: helm/example-validate
      repoURL: https://github.com/spykermj/argocd-tanka-plugin
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/environments/child_deploy.yaml
    - repoURL: https://github.com/spykermj/argo-multi-source-child
      targetRevision: HEAD
      ref: values
    - path: helm/argo-child
      repoURL: https://github.com/spykermj/argo-multi-source-child
      targetRevision: {{ .Values.deploy.gitRef }}
      helm:
        parameters:
          - name: 'deploy.gitRef'
            value: {{ .Values.deploy.gitRef }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
